var GAME_LEVELS = [
  ["                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                				",
   "                     o                o                                         				",
   "                         xx                                                     				",
   "                                                                o                				",
   "                    xxxxx     x                       x                         				",
   "                                                                                				",
   "y              x               x                                  xxxxxx        				",
   "y              x                     x                                          				",
   "yy                       xx                                          o          				",
   "yy                 o      v         xxx             xxxxxx          xxxxxxxxxx 				    ",
   "yyy              xxxx                v            o        x =       xxxxxxxx   				",
   "yyy                          x          xxxxxxx       xxxxxxxxxxxxxxxxx            				",
   "yyy@       xxxb                                     c               xxxxx     				    ",
   "xxxxxxx    xxxxxxxxy     xxxxxxxx!xxxxxx       xxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx     	    ",
   "xxxxxxx    xxxxxxxx!!!!!xxxxxxxxx!xxxxxx!!!!!!!xxxxxxxx!!!xxxxxxxxxxxxxxxx     				    ",
   "xxxxxxx!!!!xxxxxxxx!!!!!xxxxxxxxx!xxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxx     				    ",
   "xxxxxxx!!!!xxxxxxxxxxxxxxyyyyyyyyy!yyyyyxxxxxxxxxxxxxxxy!!!yyyyyxxxxxxxxxxx     ",
   "      y!!!!y             yyy!!!!!!!!!yyy               y!!!!!y                  ",
   "      y!!!!y             yyy!!!!!!!!!yyy               y!!!!!y                  ",
   "      y!!!!y             yyy!!!!!!!!!yyy               y!!!!!y                  ",
   "      y!!!!y             yyyyyyyyyyyyyyy                         xxxxxxx        ",
   "      y!!!!y                                                                    ",
   "      yyyyyy                                                                    "],
  ["                                                                                                 ",
   "                                                                                                 ",
   "                                                                                       xx        ",
   "   xxxxxxxxxxxxxxx                                              x                      xx        ",
   "   x   v     v                                                                         xx        ",
   "   x                                           x c  =     o                =       x             ",
   "   x                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "   xo     o                                    x     xxxxxx                                      ",
   "   xxxxxxxxxxxxxx      o                       x     xxxxxx     xx                               ",
   "   x                   x                       xo   xvxvxvx                             xxxxxxxxx",
   "   x               x=            bx            xx   x x x x       o                     xx       ",
   "   x=             oxxxxxxxxxxxxxxxx       x    x   xx x x x       x                     xx       ",
   "   xxxxxxxxxxxxxxxxxx                                               xxx x x x   x       xx       ",
   "                                    x                                                   xx       ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xx       ",
   "                                         xx                                          xxxxx       ",
   "                                         xx                 o  o                       xxx       ",
   "                      cxxx   xxx        xxx                    x   x                    xx       ",
   "              xxxxxxxxxx        x   x    xx  x       x     xxxxxx    x      xxxxxxxxx   xx       ",
   "         x   xxxx      xx       x o x=   xx  v       xx               x      x          xx       ",
   "     @          x      x        xxxxxxxxxxx            x     x               x o        xxx      ",
   "xxxxxxx         x      x        xxxxx  o          x     x=              x  oxxxxx    xxxxxxxx    ",
   "xxxxxxx o   =   x      x        xxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "!!!!x xxxxxxxxxxx      x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      ",
   "!!!!x xxxxxxxx         x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!                ",
   "!!!!x x!!!!!!x         x!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!!!x                     xx!!!!!!xx !                 ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                  ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                              ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                              ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                       x                                      ",
   "                                                                       x                                      ",
   "                                                                       x                                      ",
   "                                                                   x   x                                      ",
   "                                         xx                  o         x                                      ",
   "  xxx                          ox         x          o      xxxx       x                                      ",
   "  x x                         xxx         x          x                 x                                      ",
   "  x                                                                   xx                                      ",
   "  x                                     x                              x                                      ",
   "  x                                     x                    o         x                                      ",
   "  x      o                                      |xxxx|    |xxxx|xxxxxxxxxxx                                   ",
   "  x     xxxxxxxxxxx                        o o    x                                                           ",
   "  x                         xx          x                                                                     ",
   "  x                        x    xxx     x                                                                     ",
   "  x                                           x                                                               ",
   "  x      @       c xxxxxxx         x           x                     b                                        ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "               x xx    x                                                                                      ",
   " x          x    xx    x                                              ",
   "  x        x   x x x   x                                                   ",
   "   x  xx  x    x x  x  x                                                      ",
   "    x xx x     x x   x x                                                    ",
   "     xxxx      x x    xx                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                              "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
